In [6]:
import numpy as np

In [16]:
mi_np_bro = np.array([0.12,0.0012,float('inf'),0.00043])

In [11]:
np.sort(mi_np_bro)

array([0.00043, 0.0012 , 0.12   ,     inf])

In [17]:
np.cumsum(mi_np_bro)

array([0.12  , 0.1212,    inf,    inf])

In [74]:
time.get((1,2))

12

In [73]:
time

{(1, 2): 12}

In [72]:
time[(1,2)] = 12

In [71]:
time = dict()

In [47]:
from abc import ABC, abstractmethod

In [61]:
agus = np.array([0,1]) 

In [65]:
agus == agus

array([ True,  True])

In [70]:
import numpy as np
np.array_equal(agus,agus) & 1 == 1

True

In [55]:
class Search(ABC):
    
    def evaluation(self):
        print(self.initial)
        print(self.final)

In [56]:
class AStar(Search):
    def search(self):
        self.initial = 0
        self.final = 1
        self.evaluation()

In [57]:
agustin = AStar()

In [58]:
agustin.search()

0
1


In [37]:
import heapq
list_for_heapq = []
mi_np = np.array([0,1])
mi_np_3 = np.array([0,1,1])
mi_np_2 = np.array([1,0])
heapq.heappush(list_for_heapq,(-0.01,tuple(mi_np)))
heapq.heappush(list_for_heapq,(-0.025,tuple(mi_np_2)))
heapq.heappush(list_for_heapq,(-0.5,tuple(mi_np_3)))
list_for_heapq
for i in range(len(list_for_heapq)):
    print(-list_for_heapq[i][0])
    print(list_for_heapq[i][1])
    

0.5
(np.int64(0), np.int64(1), np.int64(1))
0.01
(np.int64(0), np.int64(1))
0.025
(np.int64(1), np.int64(0))


In [26]:
-float('inf')

-inf

In [25]:
import heapq

# Crear una lista de números
numeros = [10, 20, 30, 40, 50]

# Convertir los números a negativos y crear la heap
heap = [-num for num in numeros]
heapq.heapify(heap)

# Extraer el mayor número (que será el más negativo)
mayor_numero = -heapq.heappop(heap)

print(f"El mayor número es: {mayor_numero}")

El mayor número es: 50


In [22]:
mi_np = np.array([0,1])
mi_np_3 = np.array([0,1,1])
mi_np_2 = np.array([1,0])
lista = [mi_np,mi_np_2,mi_np_3]
lista

[array([0, 1]), array([1, 0]), array([0, 1, 1])]

In [24]:
lista[1:]

[array([1, 0]), array([0, 1, 1])]

In [16]:
float('inf')/2

inf

In [14]:
import numpy as np

# Supongamos que 'evaluation' es tu array de resultados de A*
evaluation = np.array([1.0, 2.0, 0.0, 4.0, 0.0, 5.0])

# Encontrar los índices donde el valor es cero
indices_cero = np.where(evaluation == 0)[0]

# Manejar la división por cero
evaluation_modificado = np.where(evaluation == 0, float('inf'), 1 / evaluation)

print(f"Índices donde ocurre la división por cero: {indices_cero}")
print(f"Array modificado: {evaluation_modificado}")

Índices donde ocurre la división por cero: [2 4]
Array modificado: [1.   0.5   inf 0.25  inf 0.2 ]


C:\Users\Agus\AppData\Local\Temp\ipykernel_27836\683701633.py:10: RuntimeWarning: divide by zero encountered in divide
  evaluation_modificado = np.where(evaluation == 0, float('inf'), 1 / evaluation)


In [13]:
import math
math.comb(2,1)

2

In [10]:
def suma(op1,op2):
    return 
variable = suma(1,2)

In [11]:
variable

In [185]:
lista_np = np.array([])

In [186]:
lista_np = np.append(lista_np,4)

In [187]:
lista_np

array([4.])

In [181]:
if(2 in np.array([0,1,3])):
    print(f'Error!')

In [175]:
patrik

array([0.25      , 0.2       , 0.16666667, 0.14285714, 0.125     ])

In [174]:
patrik = 1 / patrik

In [172]:
patrik = np.array([4,5,6,7,8])

In [ ]:
patrik = [[],[]]

In [165]:
a = [[0,1],[2,3]]

In [166]:
a = np.array(a)

In [170]:
a[1].item(1)

3

In [164]:
12%4

0

In [66]:
evaluation = [0.70,0.25,0.10]

In [159]:
fitness = [12,1,2,1,3,3,9,4,25,40]

In [141]:
fitness_2 = [12,1,2,1,3,3,9,4,25,40]

In [142]:
fitness_2 = np.array(fitness_2,dtype = float)
#fitness_2.astype(float)

In [143]:
where_are_my_values = np.argsort(fitness_2)[::-1]

In [144]:
N = len(fitness_2)

In [145]:
fitness_2 = np.sort(fitness_2)[::-1]
#fitness_2 = fitness_2[::-1]

In [146]:
fitness_2

array([40., 25., 12.,  9.,  4.,  3.,  3.,  2.,  1.,  1.])

In [147]:
fitness_2[0]

np.float64(40.0)

In [120]:
fitness_2[0] = 1

In [148]:

denominator = N**2 + N
for i in range(N):
    pos = i+1
    fitness_2[i] = (2*(N-pos+1))/denominator
fitness_2

array([0.18181818, 0.16363636, 0.14545455, 0.12727273, 0.10909091,
       0.09090909, 0.07272727, 0.05454545, 0.03636364, 0.01818182])

In [149]:
fitness_2 = fitness_2.cumsum()

In [150]:
fitness_2

array([0.18181818, 0.34545455, 0.49090909, 0.61818182, 0.72727273,
       0.81818182, 0.89090909, 0.94545455, 0.98181818, 1.        ])

In [154]:
np.where(0.2<=fitness_2)[0][0].item()

1

In [156]:
where_are_my_values

array([9, 8, 0, 6, 7, 5, 4, 2, 3, 1])

In [160]:
fitness[where_are_my_values[1]]

25

In [65]:
import numpy as np

# Array de ejemplo
array = np.array([10, 20, 15, 30, 25])

# Obtener los índices que ordenarían el array
indices_ordenados = np.argsort(array)

print("Índices que ordenarían el array:", indices_ordenados)

# Si quieres los índices en orden descendente
indices_ordenados_desc = np.argsort(array)[::-1]

print("Índices que ordenarían el array en orden descendente:", indices_ordenados_desc)

Índices que ordenarían el array: [0 2 1 4 3]
Índices que ordenarían el array en orden descendente: [3 4 1 2 0]


In [64]:
mi_lista = [1,2,3,4]

In [53]:
2**3 +1

9

In [54]:
2**(3+1)

16

In [56]:
a_1 = np.array([1,0,1])
a_2 = np.array([0,0,1])
a_3 = np.array([1,1,1])
evaluation = [(0.1,a_1),(0.7,a_2),(0.6,a_3)]

In [57]:
evaluation.sort()

In [58]:
evaluation

[(0.1, array([1, 0, 1])), (0.6, array([1, 1, 1])), (0.7, array([0, 0, 1]))]

In [62]:
evaluation.cumsum()

AttributeError: 'list' object has no attribute 'cumsum'

In [51]:
evaluation = evaluation[::-1]

In [52]:
evaluation

[(7, array([0, 0, 1])), (6, array([1, 1, 1])), (1, array([1, 0, 1]))]

In [44]:
2*3

6

In [39]:
np.argmax([1,2,3,4,5,6,7,8,9,10])

np.int64(9)

In [40]:
my_prob

array([0.25, 0.5 , 0.75])

In [41]:
my_prob.sort()

In [43]:
my_prob[::-1]

array([0.75, 0.5 , 0.25])

In [35]:
maxi = my_prob[len(my_prob)-1]

In [37]:
np.random.randfloat(0,maxi)

AttributeError: module 'numpy.random' has no attribute 'randfloat'

In [29]:
my_prob = np.cumsum(np.array([0.25,0.25,0.25]))

In [31]:
np.where(0.78<=my_prob)[0]

array([], dtype=int64)

In [27]:
np.random.rand()

0.07031563521204887

In [26]:
from enum import Enum,auto
class Crossover(Enum):
    REPLACEMENT = auto()
    TRUNCATION = auto()
    ELITISM = auto()

rawr = Crossover.REPLACEMENT
match(rawr):
    case(Crossover.REPLACEMENT):
        print('Replacement')
    case(Crossover.TRUNCATION):
        print('Truncation')
    case(Crossover.ELITISM):
        print('Elitism')

Replacement


In [21]:
class Agus:
    def cambiar(self,p):
        self.p =4
agustin = Agus()
agustin.p = 2
agustin.cambiar(agustin.p)
agustin.p

4

In [14]:
class Padre:
    def mi_funcion(self):
        self.n = 40

In [15]:
class Hijo(Padre):
    pass

In [16]:
agus = Hijo()

In [17]:
agus.mi_funcion()

In [18]:
agus.n

40

In [5]:
mi_diccionario = {(1,2):34,(3,4):35}
(1,2) in mi_diccionario

True

In [ ]:
def evaluation(self,solution):#O(n^2)
        print(f'def evaluation: Solucion antes de evaluarla {solution}')
        total_population = 0 # this is for the denominator
        min_of_all_stations_weight = float('inf') # this is for the second summatory on the evaluation function
        for idx,i in enumerate(self.problem.dictionary.get('candidates').values()): # O(n^2)
            weight_per_station = 0  # this is for the summing all the times of the candidates to a given station
            if solution[idx] == 0: # if the solution does not inlude this candidate
                continue # skip it
            pop = i.get('population')
            total_population += pop # this is just getting the total population for the denominator on the evaluation function
            station = i.get('identifier') # we fix a pointer into a candidate and we call it station
            #self.final = station
        
            for j in self.problem.dictionary.get('candidates').values(): # O(n) # we go through the candidates
                candidate = j.get('identifier')
                #self.initial = candidate
                time_a_star = self.get_time_a_star(candidate,station) # and we calculate the time it takes every candidate to reach the pointed station
                if weight_per_station < min_of_all_stations_weight:
                    min_of_all_stations_weight = weight_per_station
                #weight_per_station += time_a_star * pop
            if weight_per_station == 0:
                continue
            
                          
        #print(f'def evaluation: Solucion despues de haber hecho los calculos {solution}')
        return min_of_all_stations_weight / total_population # we return the correct ratio

In [ ]:
def proportion_based_selection(population):
        evaluation = []
        total = 0
        # 1. Evaluate each individual 
        for i in range(len(population)):
            evaluation.append(evaluation(population[i]))
            total += evaluation
        evaluation = 1/evaluation
        evaluation /= total
        import numpy as np
        # 2. Arrange the wheel
        evaluation = np.cumsum(evaluation)
        # 3. Replicate individuals according to wheel
        new_generation = []
        for i in range(len(population)):
            random_number = np.random.rand()
            solution_to_get = np.where(random_number <= evaluation)[0]
            new_generation.append(population[solution_to_get])
        return new_generation

In [3]:
import numpy as np
array_1 = np.array([1,1,1])
array_2 = np.array([2,2,2])
#solution = np.array([array_1,array_2])
#np.sum(solution)
array_1+array_2

array([3, 3, 3])

In [87]:
import numpy as np

# Función para realizar la selección por ruleta
def seleccion_por_ruleta(fitness):
    # Calcular la suma total de las funciones de aptitud
    suma_total = np.sum(fitness)
    
    # Calcular las probabilidades acumuladas
    probabilidades_acumuladas = np.cumsum(fitness / suma_total)
    
    # Generar un número aleatorio entre 0 y 1
    numero_aleatorio = np.random.rand()
    print(f'numero aleatiorio {numero_aleatorio}')
    # Encontrar el índice del primer valor que es mayor o igual al número aleatorio
    indice_seleccionado = np.where(probabilidades_acumuladas >= numero_aleatorio)[0][0]
    
    return indice_seleccionado

# Array de funciones de aptitud
fitness = np.array([0.78, 0.05, 0.20])

# Realizar la selección por ruleta
indice_padre = seleccion_por_ruleta(fitness)

print(f"El índice del padre seleccionado es: {indice_padre} ")

numero aleatiorio 0.31830924839941666
El índice del padre seleccionado es: 0 


In [70]:
list_of_evaluation_of_different_solutions = np.array([0.78,0.05,0.63,0.79])

In [54]:
list_of_evaluation_of_different_solutions = np.sort(list_of_evaluation_of_different_solutions)

In [78]:
list_of_evaluation_of_different_solutions

array([0.78, 0.05, 0.63, 0.79])

In [50]:
variable = np.random.rand()

In [65]:
variable

0.4658439148220245

In [71]:
boolean_array = variable <= list_of_evaluation_of_different_solutions

In [80]:
np.argmin(list_of_evaluation_of_different_solutions).item()

1

In [84]:
np.argmax(boolean_array).item()

0

In [82]:
index_first_true = np.argmax(boolean_array) if np.argmax(boolean_array) == np.argmin(list_of_evaluation_of_different_solutions) 

SyntaxError: expected 'else' after 'if' expression (2454866119.py, line 1)

In [68]:
index_first_true.item()

1

In [69]:
list_of_evaluation_of_different_solutions[index_first_true].item()

0.63

In [46]:
import numpy as np
np.cumsum([1,2,3,4,5,6,7,8,9,10])


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [42]:
        import numpy as np
        length_of_array_of_candidates = 5
        number_of_ones_we_need = 2
        random_solution = np.zeros(length_of_array_of_candidates,dtype=int)
        positions_where_we_are_going_to_introduce_ones = np.random.choice(length_of_array_of_candidates,number_of_ones_we_need,replace = False)
        random_solution[positions_where_we_are_going_to_introduce_ones] = 1
        random_solution

array([0, 0, 1, 0, 1])

In [105]:
import heapq
mi_heap = []

In [121]:
heapq.heappush(mi_heap,(1.45,np.array([1,2,2])))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [118]:
mi_heap

[(1.45, [1, 2, 4])]

In [120]:
heapq.heappop(mi_heap)

(1.45, [1, 2, 2])

In [102]:
mi_lista_de_nps = [np.array([1,2]),np.array([3,4])]

In [103]:
mi_lista_de_nps[0]

array([1, 2])

In [104]:
mi_lista_de_nps.any()

AttributeError: 'list' object has no attribute 'any'

In [101]:
import numpy as np
np.random.choice(range(2,7)).item()
# range(2,7)

5

In [75]:
# Python program explaining 
# numpy.concatenate() function 
  
# importing numpy as geek  
import numpy as geek 
  
arr1 = geek.array([[2, 4], [6, 8]]) 
arr2 = geek.array([[3, 5], [7, 9]]) 
  
gfg = geek.concatenate((arr1, arr2), axis = None) 
  
print (gfg) 

[2 4 6 8 3 5 7 9]


In [53]:
import numpy as np


In [54]:
mi_np = np.array([1,2,3,4])

In [55]:
mi_np[:-1]

array([1, 2, 3])

In [63]:
mi_np[2:]

array([3, 4])

In [64]:
mi_np[:2]

array([1, 2])

In [68]:
mi_np[:2]

array([1, 2])

In [76]:
np.concatenate((mi_np[:2],mi_np[2:]),axis=None)

array([1, 2, 3, 4])

In [59]:
mi_np[:2] + mi_np[2:]

array([4, 6])

In [65]:
np.concatenate(np.array(mi_np[:2]),np.array(mi_np[2:]),axis = None)

TypeError: concatenate() got multiple values for argument 'axis'

In [67]:
np.concatenate([1,2],[3,4],None)

TypeError: 'list' object cannot be interpreted as an integer

In [45]:
parent_one = deque([1,2,3])
parent_two = deque([4,5,6])

In [46]:
parent_two[:2]

TypeError: sequence index must be integer, not 'slice'

In [47]:
mi_lista = [1,2,3]

In [51]:
mi_lista = mi_lista[:-1]

In [52]:
mi_lista

[1, 2]

In [36]:
from collections import deque

In [37]:
mi_array = deque([1,2,3])

In [38]:
len(mi_array)

3

In [44]:
type(int(len(mi_array)/3))

int

In [40]:
class(3)

SyntaxError: invalid syntax (747416768.py, line 1)

In [41]:
type(2)

int

In [21]:
import numpy as np


In [29]:
mi_np = np.array([0,1,0])

In [35]:
mi_np

array([0, 0, 0])

In [23]:
mi_np[0]

np.int64(0)

In [24]:
mi_np[1]

np.int64(1)

In [28]:
mi_np.item(2)

0

In [34]:
mi_np[1] = 0

In [2]:
mi_lista = [1,2,3,4]

In [3]:
mi_lista[:2]

[1, 2]

In [4]:
mi_lista[:-3]

[1]

In [5]:
mi_lista[-1:]

[4]

In [6]:
mi_lista[:-1]

[1, 2, 3]

In [7]:
mi_lista[-1:]

[4]

In [8]:
mi_lista[:-1]

[1, 2, 3]

In [10]:
mi_lista[0]

1

In [11]:
mi_lista[1:]

[2, 3, 4]

In [12]:
mi_lista[:1]

[1]

In [13]:
mi_lista[:2]

[1, 2]

In [14]:
mi_lista[:3]

[1, 2, 3]

In [15]:
mi_lista[3:]

[4]

In [18]:
mi_lista = [1,2,3]

In [19]:
mi_lista_dos = [4,5]

In [20]:
mi_lista + mi_lista_dos

[1, 2, 3, 4, 5]

In [126]:
import random
random.uniform(0,1)

0.11647169819266923

In [77]:
import numpy as np
np.random.choice(1)

0

In [63]:
import numpy as np
heyhey = [0,10,0,1,0,1,1]
len(heyhey)
#for i in range(len(heyhey)):
#    print(i)
np.random.choice(range(len(heyhey)))+1

np.int64(1)

In [38]:
import numpy as np
from itertools import combinations

def generar_vecinos(array, k):
    n = len(array)
    mitad_k = k // 2
    
    # Seleccionar aleatoriamente los índices que permanecerán fijos
    indices = np.arange(n)
    np.random.shuffle(indices)
    indices_fijos = indices[:mitad_k]
    indices_cambiables = indices[mitad_k:k]
    
    # Generar todas las combinaciones posibles de los bits cambiables
    combinaciones = list(combinations(indices_cambiables, mitad_k))
    
    vecinos = []
    for comb in combinaciones:
        nuevo_vecino = array.copy()
        for idx in comb:
            nuevo_vecino[idx] = 1 - nuevo_vecino[idx]  # Cambia el bit
        vecinos.append(nuevo_vecino)
    
    return vecinos

# Ejemplo de uso
array = np.array([1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])
k = 4
vecinos = generar_vecinos(array, k)
for vecino in vecinos:
    print(vecino)

[1 0 1 0 0 1 0 1 0 1 0 1 1 0 0]


In [111]:
import random

def intercambiar_uno_cero(array):
    # Encuentra los índices de todos los 1s y 0s en el array
    indices_unos = [i for i, bit in enumerate(array) if bit == 1]
    indices_ceros = [i for i, bit in enumerate(array) if bit == 0]
    
    if not indices_unos or not indices_ceros:
        return array  # Si no hay 1s o 0s, devuelve el array original
    
    # Selecciona un índice aleatorio de los 1s y un índice aleatorio de los 0s
    indice_uno = random.choice(indices_unos)
    indice_cero = random.choice(indices_ceros)
    
    # Intercambia los bits seleccionados
    array[indice_uno], array[indice_cero] = array[indice_cero], array[indice_uno]
    
    return array

# Ejemplo de uso
array = [1, 0, 1, 0, 0]
nuevo_array = intercambiar_uno_cero(array)
print(nuevo_array)

[1, 1, 0, 0, 0]


In [116]:
import numpy as np

def intercambiar_uno_cero(array):
    # Encuentra los índices de todos los 1s y 0s en el array
    indices_unos = np.where(array == 1)[0]
    indices_ceros = np.where(array == 0)[0]
    
    if len(indices_unos) == 0 or len(indices_ceros) == 0:
        return array  # Si no hay 1s o 0s, devuelve el array original
    
    # Selecciona un índice aleatorio de los 1s y un índice aleatorio de los 0s
    indice_uno = np.random.choice(indices_unos)
    indice_cero = np.random.choice(indices_ceros)
    
    # Intercambia los bits seleccionados
    array[indice_uno], array[indice_cero] = array[indice_cero], array[indice_uno]
    
    return array

# Ejemplo de uso
array = np.array([1, 0, 1, 0, 0])
nuevo_array = intercambiar_uno_cero(array)
print(nuevo_array)

[1 0 0 1 0]


In [183]:
np.random.choice(range(3))+1

np.int64(2)

In [89]:
mi_lista = [0,1,0]
np.random.shuffle(mi_lista)
mi_lista

[0, 0, 1]

In [98]:
np.random.choice([1,2])

np.int64(1)

In [ ]:
np.

In [86]:
import random

def shuffle_un_bit(array):
    # Encuentra los índices de todos los 0s en el array
    indices_ceros = [i for i, bit in enumerate(array) if bit == 0]
    
    if not indices_ceros:
        return array  # Si no hay 0s, devuelve el array original
    
    # Selecciona un índice aleatorio de los 0s
    indice_seleccionado = random.choice(indices_ceros)
    
    # Cambia el bit seleccionado a 1
    array[indice_seleccionado] = 1
    
    return array

# Ejemplo de uso
array = [1, 0, 1, 0, 0]
nuevo_array = shuffle_un_bit(array)
print(nuevo_array)

[1, 0, 1, 1, 0]


In [85]:
import numpy as np

def generar_vecinos_filtrados(estado_inicial, num_vecinos=10):
    vecinos = set()
    estado_inicial = np.array(estado_inicial)
    
    while len(vecinos) < num_vecinos:
        vecino = estado_inicial.copy()
        np.random.shuffle(vecino)
        if np.any(np.logical_and(vecino, estado_inicial)):
            vecino_tuple = tuple(vecino)  # Convertir a tupla para agregar al conjunto
            vecinos.add(vecino_tuple)
    
    # Convertir el conjunto de tuplas de vuelta a una lista de listas
    vecinos = [list(vecino) for vecino in vecinos]
    
    return vecinos

# Ejemplo de uso
estado_inicial = [1, 0, 1, 0]
vecinos = generar_vecinos_filtrados(estado_inicial, num_vecinos=5)
for vecino in vecinos:
    print(vecino)

[np.int64(1), np.int64(1), np.int64(0), np.int64(0)]
[np.int64(0), np.int64(1), np.int64(1), np.int64(0)]
[np.int64(1), np.int64(0), np.int64(1), np.int64(0)]
[np.int64(1), np.int64(0), np.int64(0), np.int64(1)]
[np.int64(0), np.int64(0), np.int64(1), np.int64(1)]


In [78]:
import math

def combinaciones(n, k):
    return math.comb(n, k)

# Ejemplo de uso
n = 3
for k in range(n + 1):
    print(f"Combinaciones de {n} posiciones con {k} unos: {combinaciones(n, k)}")

Combinaciones de 3 posiciones con 0 unos: 1
Combinaciones de 3 posiciones con 1 unos: 3
Combinaciones de 3 posiciones con 2 unos: 3
Combinaciones de 3 posiciones con 3 unos: 1


In [82]:
import numpy as np
import math
def generar_vecinos(estado_inicial):
    vecinos = []
    estado_inicial = np.array(estado_inicial)
    
    for _ in range(math.comb(len(estado_inicial),1)):
        vecino = estado_inicial.copy()
        np.random.shuffle(vecino)
        vecinos.append(vecino.tolist())
    
    return vecinos

# Ejemplo de uso
estado_inicial = [1, 0]
vecinos = generar_vecinos(estado_inicial)
for vecino in vecinos:
    print(vecino)

[0, 1]
[1, 0]


In [72]:
import numpy as np

In [75]:
mi_solucion = np.array([])

In [76]:
mi_solucion[0]

IndexError: index 0 is out of bounds for axis 0 with size 0

In [70]:
def suma(op1,op2):
    return op1 + op2

In [71]:
import unittest
class TestSuma(unittest.TestCase):
    def test_case_1(self):
        self.assertEqual(suma(1,2),3) # Suponiendo que mi funcion deberia devolver 3
if __name__=='__main__':
    unittest.main()

E
ERROR: C:\Users\Agus\AppData\Roaming\jupyter\runtime\kernel-38f2dbab-c0f7-4894-b33f-25d6ffdba4f8 (unittest.loader._FailedTest.C:\Users\Agus\AppData\Roaming\jupyter\runtime\kernel-38f2dbab-c0f7-4894-b33f-25d6ffdba4f8)
----------------------------------------------------------------------
AttributeError: module '__main__' has no attribute 'C:\Users\Agus\AppData\Roaming\jupyter\runtime\kernel-38f2dbab-c0f7-4894-b33f-25d6ffdba4f8'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


SystemExit: 1

C:\Users\Agus\AppData\Local\Programs\Python\Python312\Lib\site-packages\IPython\core\interactiveshell.py:3585: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [12]:
class Father:
    def __init__(self):
        self.n = 8

In [13]:
class Child(Father):
    pass

In [14]:
padre = Father()

In [15]:
padre.n

8

In [16]:
hijo = Child()

In [17]:
hijo.n

8

**Lab 2** Assignment

*Agustín Prieto*

*Jesús Sanz*

We need the **Node** class for the **momento** technique when using the priorityQueue **heapq** library

What the **heapq** library does is keep track of the **priority** and when you do *heapq.pop* it gets you the one with less value in the priority field

In [1]:
class Node:
    def __init__(self,parent,state,action,depth,accumulatedCost):
        self.parent = parent
        self.state = state # we want it to be type State
        self.action = action # the same with action is going to be a class
        self.depth = depth
        self.accumulatedCost = accumulatedCost # this way it's easier to compute g(n) on f(n) = g(n)+h(n)
        self.momento = 0
    def __str__(self):
        stringToReturn = (
        f'parent --> { self.parent}\n'
        f'state --> { self.state.state}\n'
        f'action --> (origin, destination,cost) --> ({self.action.origin} , {self.action.destination}, {self.action.cost})\n'
        f'depth -->  {self.depth}'
        )
        return stringToReturn
    def __lt__(self,obj):
        return self.momento < obj.momento

I am going to copy the **State** class as well, just in case. Notice that the **Node** class has an attribute state of type **State**

In [4]:
class State:
    def __init__(self,state,longitude,latitude):
        self.state = state
        self.longitude = longitude
        self.latitude = latitude

I am putting **Action** class as well since it is used in **AStar** search.

In [5]:
class Action: 
    def __init__(self,origin,destination,cost):
        self.origin = origin
        self.destination = destination
        self.cost = cost
    def __str__(self):
       return(
           f' {self.origin} → {self.destination} ({self.cost})'
       )

In [18]:
import json
class Agustin:
    def __init__(self):
        self.dictionary = None
        with open('calle_del_virrey_morcillo_albacete_250_3_candidates_15_ns_4.json','r') as file:
             self.dictionary = json.load(file)
        self.dictionary['intersections'] = {inter['identifier']: inter for inter in self.dictionary.get('intersections')}# O(m)
        
        # Add the 'whereto' attribute to each intersection
        for inter in self.dictionary['intersections'].values():# O(m)
            inter['whereto'] = []

        # Populate the 'whereto' attribute based on the segments
        for segment in self.dictionary.get('segments'):# O(n)
            origin = segment['origin']#O(1)
            destination = segment['destination'] #O(1)
            distance = segment['distance'] #O(1)
            speed_kmh = segment['speed'] # O(1)

            # Convert speed from km/h to m/s
            speed_ms = speed_kmh * (1000 / 3600)
            #self.dictionary['mostRepeatedSpeed'].append(speed_ms)
            # Si tenemos una velocidad mayor a la predeterminada, la cogemos
            #if(speed_ms > self.dictionary.get('maxSpeedOfAllSpeeds')):#O(1)
            #    self.dictionary['maxSpeedOfAllSpeeds'] = speed_ms
    
            # Calculate the cost
            cost = distance / speed_ms
    
            # Add the destination and cost to the 'whereto' attribute of the origin intersection
            #if origin in self.dictionary.get('intersections'): # O(1)
            self.dictionary.get('intersections').get(origin).get('whereto').append({'id': destination, 'cost': cost})
        #for i in self.dictionary.get('intersections'):
        #    self.dictionary.get(i)['whereto'] = sorted(self.dictionary.get('whereto'),key = lambda x:x['id'])
        for i in self.dictionary.get('intersections'):
            self.dictionary['intersections'][i]['whereto'] = sorted(self.dictionary.get('intersections').get(i).get('whereto'),key = lambda x:x['id'])

In [19]:
agus = Agustin()

In [20]:
agus.dictionary.get('candidates')
agus.dictionary['candidates'] = {candidate[0]:{"identifier":candidate[0],"population":candidate[1]} for candidate in agus.dictionary.get('candidates')}

In [21]:
agus.dictionary.get('candidates')

{955316231: {'identifier': 955316231, 'population': 875},
 1736146191: {'identifier': 1736146191, 'population': 1827},
 11303171544: {'identifier': 11303171544, 'population': 733},
 430968594: {'identifier': 430968594, 'population': 661},
 430968596: {'identifier': 430968596, 'population': 397},
 434369348: {'identifier': 434369348, 'population': 836},
 430968590: {'identifier': 430968590, 'population': 534},
 2000100687: {'identifier': 2000100687, 'population': 1376},
 2783160954: {'identifier': 2783160954, 'population': 1486},
 1534218794: {'identifier': 1534218794, 'population': 145},
 431043029: {'identifier': 431043029, 'population': 1409},
 1255528482: {'identifier': 1255528482, 'population': 1726},
 435465434: {'identifier': 435465434, 'population': 1436},
 1257471997: {'identifier': 1257471997, 'population': 223},
 2822641953: {'identifier': 2822641953, 'population': 1293}}

In [22]:
enumerate(agus.dictionary.get('candidates').values())

In [29]:
for idx,i in enumerate(agus.dictionary.get('candidates').values()):
    print(f'idx --> {idx}')
    print(i)

idx --> 0
{'identifier': 955316231, 'population': 875}
idx --> 1
{'identifier': 1736146191, 'population': 1827}
idx --> 2
{'identifier': 11303171544, 'population': 733}
idx --> 3
{'identifier': 430968594, 'population': 661}
idx --> 4
{'identifier': 430968596, 'population': 397}
idx --> 5
{'identifier': 434369348, 'population': 836}
idx --> 6
{'identifier': 430968590, 'population': 534}
idx --> 7
{'identifier': 2000100687, 'population': 1376}
idx --> 8
{'identifier': 2783160954, 'population': 1486}
idx --> 9
{'identifier': 1534218794, 'population': 145}
idx --> 10
{'identifier': 431043029, 'population': 1409}
idx --> 11
{'identifier': 1255528482, 'population': 1726}
idx --> 12
{'identifier': 435465434, 'population': 1436}
idx --> 13
{'identifier': 1257471997, 'population': 223}
idx --> 14
{'identifier': 2822641953, 'population': 1293}


In [56]:
import numpy as np
length_of_array_of_candidates = len(agus.dictionary.get('candidates'))
number_of_ones_we_need = agus.dictionary.get('number_stations')
random_solution = np.zeros(length_of_array_of_candidates,dtype=int)
positions_where_we_are_going_to_introduce_ones = np.random.choice(length_of_array_of_candidates,number_of_ones_we_need,replace = False)
random_solution[positions_where_we_are_going_to_introduce_ones] = 1
solution = random_solution

In [63]:
        total_population = 0 # this is for the denominator
        weight_per_station = 0 # this is for the summing all the times of the candidates to a given station
        min_of_all_stations_weight = float('inf') # this is for the second summatory on the evaluation function
        for id,i in enumerate(agus.dictionary.get('candidates').values()):
            if solution[id] == 0: # if the solution does not inlude this candidate
                continue # skip it
            pop = i.get('population')
            total_population += pop # this is just getting the total population for the denominator on the evaluation function
            station = i.get('identifier') # we fix a pointer into a candidate and we call it station
            #self.final = station
        
            for j in agus.dictionary.get('candidates').values(): # we go through the candidates
                candidate = j.get('identifier')
                #self.initial = candidate
                time_a_star = get_time_a_star(candidate,station) # and we calculate the time it takes every candidate to reach the pointed station
                weight_per_station += time_a_star * pop * solution[id]
            if weight_per_station < min_of_all_stations_weight:
                min_of_all_stations_weight = weight_per_station
            weight_per_station = 0                

ModuleNotFoundError: No module named 'Node'

In [62]:
def get_time_a_star(initial,final):
        
        if( not is_already_in_memory(initial,final)): # if it is NOT in memory
            # save it in memory
            return save_changes(initial,final)
        #otherwise just get it from memory
        return problem.dictionary.get('candidates').get(initial).get('time').get(final).get('A*')# get it from memory

In [61]:
def is_already_in_memory(initial,final):
        if ('time' in agus.dictionary.get('candidates').get(initial)):
            for i in agus.dicitonary.get('candidates').get(initial).get('time').values():
                if(i.get('identifier') == final):
                    return True
        return False

In [60]:
def save_changes(initial,final):
        """
        The idea is saving a dictionary of dictionaries ('time') which for each candidate will store 
        where it can go and how much time it costs

        {'candidate1':{'identifier':,'population':,'time': {'identifier':,'A*':}},
        'candidate2':{'identifier':,'population':,'time':{'identifier':,'A*':}}}
        """
        #from AStar import AStar
        instance_of_search = AStar(agus.dictionary)
        time_a_star = instance_of_search.search(initial,final)
        if(not 'time' in self.problem.dictionary.get('candidates').get(initial)):
            self.problem.dictionary.get('candidates').get(initial)['time'] = dict()        
        self.problem.dictionary.get('candidates').get(initial).get('time')[final] ={'identifier':final,'A*':time_a_star}
        return time_a_star

In [59]:
class AStar(Search):# takes into account g(n), not only h(n)
    ##############################################################################################
    ############################################# insert #########################################
    ##############################################################################################
    def insert(self,element,goalId):
         # element is a node
        """self.openDS is by default a deque() (see Search __init__) so we
        have to convert deque() into a list"""
        self.openDS = list(self.openDS)
        heuristic = (self.computeHeuristic(element,goalId)/self.problem.dictionary.get('maxSpeedOfAllSpeeds'))+element.accumulatedCost
        #print('\n-----------\n'.join(map(str,self.openDS)))
        heapq.heappush(self.openDS,(heuristic,element)) # element is going to be a paired value (h,Node)
    ##############################################################################################
    ############################################ extract #########################################
    ##############################################################################################
    def extract(self): #O(1)
        # tenemos que extraer el que menor heurística tiene --> la heurística hace de prioridad
        return heapq.heappop(self.openDS)[1] # heapq es una priorityQueue sin ser una Queue sino una Heap
    ##############################################################################################
    ######################################## computeHeuristic ####################################
    ##############################################################################################
    def computeHeuristic(self,node_param,goalId): #O(1)
        """self.openDS is by default a deque() (see Search __init__) so we
        have to convert deque() into a list"""
        self.openDS = list(self.openDS) # medios para obtener lo que queremos
        #goalId = self.final # Obtenemos estado final
        coord_1 = (node_param.state.longitude, node_param.state.latitude) # (longitude,latitude)
        coord_2 = (self.problem.dictionary.get('intersections').get(goalId).get('longitude'), 
        self.problem.dictionary.get('intersections').get(goalId).get('latitude'))  # (longitude,latitude)
        # Usar el elipsoide WGS84 para calcular la distancia
        geod = Geodesic.WGS84 # cosas de la librería
        resultado = geod.Inverse(coord_1[0], coord_1[1], coord_2[0], coord_2[1]) # cosas de la librería
        # Distancia en metros
        distancia = resultado['s12'] 
        return distancia
         ##############################################################################################
    ######################################### search #########################################
    ##############################################################################################
    def search(self,initial,final): # O(n) # y siempre buscamos de la misma forma
        """:param search_param: strategy to use
        
        :returns: empty list of list of actions"""
        self.initializeOpen(initial) # inicializo nodo raiz # O(1)
        self.insert(self.root,final)
        while len(self.openDS)!=0:    
            node = self.extract() # O(1) 
            #self.exploredNodes +=1
            if node.state.state not in self.explored:
                if(self.testGoal(node,final)): 
                    self.depth = node.depth
                    self.totalCost = node.accumulatedCost
                    return node.accumulatedCost # the accumulated cost of the last node is the total cost of the path and that is exactly what we want
                successors1 = self.expand(node) # O(n)
                #if (len(successors1)>0):
                #    self.expandedNodes+=1
                for  successor in successors1: # O(n)
                    self.insert(successor,final) # O(1)
                self.explored.add(node.state.state) #  node.state es el objeto y node.state.state es la variable en el objeto state
        print("Solución no encontrada y hemos recorrido todo el árbol")
        # if A* gives an NaN result, we are going to be here since there is no path
        return 0 # we return 0 to not take into account this solution as there is no path really
    """notice that we work with a tuple
    so if we want to return a node we must say tuple[1]
    where the tuple is (heuristic,node)"""
    ##############################################################################################
    ######################################## initializeOpen ######################################
    ##############################################################################################
    def initializeOpen(self,initial): # O(1)
        longitudeInitialNode = agus.dictionary.get('intersections').get(initial).get('longitude')
        latitudeInitialNode = agus.dictionary.get('intersections').get(initial).get('latitude')
        from Node import Node
        from State import State
        from Action import Action
        self.root = Node(None,State(initial,longitudeInitialNode,latitudeInitialNode),Action(None,initial,0),0,0) # no estoy seguro si para llegar al nodo raiz action == None
        self.nodesGenerated+=1
        self.root.momento = self.nodesGenerated
    #################################################################################
    ####################             testGoal              ##########################
    #################################################################################
    def testGoal(self,node,final):# O(1)
        return final == node.state.state# node.state es de tipo State y node.state.state es de tipo int

In [58]:
class Search:
    def __init__(self,problem):
        self.problem = problem
        self.openDS = [] # open_data_structure
        self.explored = {0}
        self.nodesGenerated = 0
        #self.initial = 0
        #self.final = 0
    def insert(self,element): # siempre insertamos de la misma forma
        self.openDS.append(element)
    #@abstractmethod
    def extract():
        pass
    #@abstractmethod
    ##############################################################################################
    ######################################### evaluation #########################################
    ##############################################################################################
    def evaluation(self,solution):
        """
        Here is where we are going to store in memory the results of A* so that if in a near future we need it,
        we can go and look in memory, not performing all the calculations again. Also, bear in mind what was mentioned
        in the lab that if we are trying to minimize then we must take f_ = 1/f. In other words, if you want the
        highest score of the class, you want to transform a 10 to a 1/10 so that it is the smallest one of all.
        If you divide 1 over a number that is greater, then the ratio is going to be smaller.
        1/10 < 1/9. 10 is a better grade than 9 and as you want to keep the same information but minimizing,
        that is why we do the ratio. So, maybe we are going to have to do this here. We want to minimize the time
        we spend to go to a certain Service Station.

        Somehow here you are taking the best station. We are doing the minimum between the different sums of all the 
        times that take all the candidates to reach a given station. I don't think I am making myself clear. 
        We compute the time it takes every candidate to go to a given station and sum this times. We repeat the
        process for the rest of the candidates and we take the minimum. In essence, we are taking the candidate
        that minimizes this time (the sum of the time it takes the rest of candidates to reach this station). 
        :param solution: a given solution to be evaluated 
        """
        total_population = 0 # this is for the denominator
        weight_per_station = 0 # this is for the summing all the times of the candidates to a given station
        min_of_all_stations_weight = float('inf') # this is for the second summatory on the evaluation function
        for idx,i in enumerate(self.problem.dictionary.get('candidates').values()):
            if solution[idx] == 0: # if the solution does not inlude this candidate
                continue # skip it
            pop = i.get('population')
            total_population += pop # this is just getting the total population for the denominator on the evaluation function
            station = i.get('identifier') # we fix a pointer into a candidate and we call it station
            self.final = station
        
            for j in self.problem.dictionary.get('candidates').values(): # we go through the candidates
                candidate = j.get('identifier')
                self.initial = candidate
                time_a_star = self.get_time_a_star(candidate,station) # and we calculate the time it takes every candidate to reach the pointed station
                weight_per_station += time_a_star * pop * solution[idx]
            if weight_per_station < min_of_all_stations_weight:
                min_of_all_stations_weight = weight_per_station
            weight_per_station = 0                
        return min_of_all_stations_weight / total_population # we return the correct ratio
  ##############################################################################################
    ######################################### get_time_a_star #########################################
    ##############################################################################################
    def get_time_a_star(self,initial,final):
        
        if( not self.is_already_in_memory(initial,final)): # if it is NOT in memory
            # save it in memory
            return self.save_changes(initial,final)
        #otherwise just get it from memory
        return self.problem.dictionary.get('candidates').get(initial).get('time').get(final).get('A*')# get it from memory
           ##############################################################################################
    ######################################### is_already_in_memory #########################################
    ##############################################################################################
    def is_already_in_memory(self,initial,final):
        if ('time' in self.problem.dictionary.get('candidates').get(initial)):
            for i in self.problem.dictionary.get('candidates').get(initial).get('time').values():
                if(i.get('identifier') == final):
                    return True
        return False
        ##############################################################################################
    ######################################### save_changes #########################################
    ##############################################################################################
    def save_changes(self,initial,final):
        """
        The idea is saving a dictionary of dictionaries ('time') which for each candidate will store 
        where it can go and how much time it costs

        {'candidate1':{'identifier':,'population':,'time': {'identifier':,'A*':}},
        'candidate2':{'identifier':,'population':,'time':{'identifier':,'A*':}}}
        """
        from AStar import AStar
        instance_of_search = AStar(self.problem)
        time_a_star = instance_of_search.search(initial,final)
        if(not 'time' in self.problem.dictionary.get('candidates').get(initial)):
            self.problem.dictionary.get('candidates').get(initial)['time'] = dict()        
        self.problem.dictionary.get('candidates').get(initial).get('time')[final] ={'identifier':final,'A*':time_a_star}
        return time_a_star
            
    def search(self):
       pass
    ##############################################################################################
    ############################## correctPossibleNumberStations #################################
    ##############################################################################################
    def correctPossibleNumberStations(self,configuration):
        """
        In this function we correct the number of ceros and ones to our needs.
        :param configuration: ndarray from numpy library representing a binary array, a configuration, a solution, a chromosome
        """
        # we get the number of ones
        number_of_ones_we_must_have = self.problem.dictionary.get('number_stations')
        number_of_ones_we_have = np.count_nonzero(configuration==1)
        if (number_of_ones_we_have < number_of_ones_we_must_have):
            # we must introduce some ones
            difference = number_of_ones_we_must_have - number_of_ones_we_have
            positions_where_zeros_are = np.where(configuration == 0)[0]
            new_positions_ones = np.random.choice(positions_where_zeros_are,difference, replace = False)
            configuration[new_positions_ones] = 1
        if (number_of_ones_we_have > number_of_ones_we_must_have):
            # we compute the difference 
            difference =  number_of_ones_we_have - number_of_ones_we_must_have
            positions_where_ones_are = np.where(configuration==1)[0]
            new_positions_zero = np.random.choice(positions_where_ones_are,difference,replace = False)
            configuration[new_positions_zero] = 0
        return configuration
    ##############################################################################################
    ################################### generateARandomSolution ##################################
    ##############################################################################################
    def generateARandomSolution(self):
        """
        Function to create a random solution.
        
        """
        length_of_array_of_candidates = len(self.problem.dictionary.get('candidates'))
        number_of_ones_we_need = self.problem.dictionary.get('number_stations')
        random_solution = np.zeros(length_of_array_of_candidates,dtype=int)
        positions_where_we_are_going_to_introduce_ones = np.random.choice(length_of_array_of_candidates,number_of_ones_we_need,replace = False)
        random_solution[positions_where_we_are_going_to_introduce_ones] = 1
        return random_solution
    ##############################################################################################
    ######################################## hillClimbing ########################################
    ##############################################################################################
    def hillClimbing(self,initialSolution):
        """
        This is where we exploit, hill climb. We revise our neighbours.
        """
        #Lesson 7 Slide 13
        currentSolution = initialSolution
        currentScore = self.evaluation(currentSolution)
        improves = True
        while (improves):
            improves = False
            neighbours = self.generateNeighbours(currentSolution)
            for neighbour in neighbours:
                score = self.evaluation(neighbour)
                if (score > currentScore):
                    currentSolution = neighbour
                    currentScore = score
                    improves = True
        return currentScore
    ##############################################################################################
    ######################################## generateNeighbours ##################################
    ##############################################################################################
    def generateNeighbours(self,currentSolution):
        """
        We generate neighbours by just changing one bit at a time. Permutation.
        Notice that all the neighbours are not valid solutions. Maybe we can optimize this in a future.
        """
        neighbours = []
        for i in range(0,len(currentSolution)): # for the length of the array
            neighbour_ = currentSolution.copy()

            neighbour_[i] = 1 - neighbour_[i] # 1-0 is 1 and 1-1 = 0 so that we change the bit 
            condition = self.checkIfThisIsASolution(neighbour_) # if it is a valid solution
            if (condition):
                neighbours.append(neighbour_) # we put it into our bag of solutions
                
        return np.array(neighbours)
    ##############################################################################################
    ######################################## checkIfThisIsASolution ##############################
    ##############################################################################################
    def checkIfThisIsASolution(self,solution):
        """
        Checks if a given solution is valid.
        :param solution: given solution
        :return boolean: returns a boolean
        """
        number_of_ones_in_this_solution = np.count_nonzero(solution==1) # gets the number of zeros we have in the solution passed by parameter
        return number_of_ones_in_this_solution == self.problem.dictionary.get('number_stations') # returns true if it has the number of stations 
        #we must submit
    #################################################################################
    ####################             expand             ############################
    #################################################################################
    def expand(self,Node_param): #O(n)
        """ 
        :param Node_param: nodo al que apuntamos 
        :returns: list of nodes """
        successors = []
        currentIntersection = self.problem.dictionary.get('intersections').get(Node_param.state.state) # O(1)

        listOrdered = sorted(currentIntersection.get("whereto"), key = lambda x:x['id']) # O(n*log(n)) # Timsort
        for destination in listOrdered: # O(n)
            """currentIntersection.get("whereto")
            [{'id': 1256026663, 'cost': 1.7331}, {'id': 1531659796, 'cost': 2.346}]"""
            if destination.get('id') in self.explored: # O(1) # preguntamos si ya lo hemos recorrido
                continue
            from Action import Action
            newAction = Action(# O(1)
                    Node_param.state.state, #origen
                    destination.get("id"), # destino
                    destination.get("cost") #coste
                )
            # REMEMBER THAT destination is A DICTIONARY {"id":,"cost":}
            from State import State
            newState = State(newAction.destination,self.problem.dictionary.get('intersections').get(destination.get('id')).get('longitude'),self.problem.dictionary.get('intersections').get(destination.get('id')).get('latitude')) #self.applyAction(Node_param.state,action) # Node.state es un objeto de tipo state
            from Node import Node
            newNode = Node(Node_param,newState,newAction,Node_param.depth+1,Node_param.accumulatedCost+newAction.cost)
            self.nodesGenerated+=1
            newNode.momento = self.nodesGenerated
            successors.append(newNode)
        return successors

In [52]:
agus.dictionary.get('candidates')

{955316231: {'identifier': 955316231, 'population': 875},
 1736146191: {'identifier': 1736146191, 'population': 1827},
 11303171544: {'identifier': 11303171544, 'population': 733},
 430968594: {'identifier': 430968594, 'population': 661},
 430968596: {'identifier': 430968596, 'population': 397},
 434369348: {'identifier': 434369348, 'population': 836},
 430968590: {'identifier': 430968590, 'population': 534},
 2000100687: {'identifier': 2000100687, 'population': 1376},
 2783160954: {'identifier': 2783160954, 'population': 1486},
 1534218794: {'identifier': 1534218794, 'population': 145},
 431043029: {'identifier': 431043029, 'population': 1409},
 1255528482: {'identifier': 1255528482, 'population': 1726},
 435465434: {'identifier': 435465434, 'population': 1436},
 1257471997: {'identifier': 1257471997, 'population': 223},
 2822641953: {'identifier': 2822641953, 'population': 1293}}

In [53]:
'time' in agus.dictionary.get('candidates').get(955316231)

False

In [54]:
agus.dictionary.get('intersections').get(430968565)

{'identifier': 430968565,
 'longitude': -1.8602834,
 'latitude': 38.9991511,
 'whereto': [{'id': 1257471995, 'cost': 6.619199999999999},
  {'id': 1529477842, 'cost': 10.40604}]}

In [55]:
agus.dictionary.get('candidates').get(955316231)['time'] = dict()

In [56]:
agus.dictionary.get('candidates')

{955316231: {'identifier': 955316231, 'population': 875, 'time': {}},
 1736146191: {'identifier': 1736146191, 'population': 1827},
 11303171544: {'identifier': 11303171544, 'population': 733},
 430968594: {'identifier': 430968594, 'population': 661},
 430968596: {'identifier': 430968596, 'population': 397},
 434369348: {'identifier': 434369348, 'population': 836},
 430968590: {'identifier': 430968590, 'population': 534},
 2000100687: {'identifier': 2000100687, 'population': 1376},
 2783160954: {'identifier': 2783160954, 'population': 1486},
 1534218794: {'identifier': 1534218794, 'population': 145},
 431043029: {'identifier': 431043029, 'population': 1409},
 1255528482: {'identifier': 1255528482, 'population': 1726},
 435465434: {'identifier': 435465434, 'population': 1436},
 1257471997: {'identifier': 1257471997, 'population': 223},
 2822641953: {'identifier': 2822641953, 'population': 1293}}

In [57]:
for i in agus.dictionary.get('candidates').values():
    print(i)

{'identifier': 955316231, 'population': 875, 'time': {}}
{'identifier': 1736146191, 'population': 1827}
{'identifier': 11303171544, 'population': 733}
{'identifier': 430968594, 'population': 661}
{'identifier': 430968596, 'population': 397}
{'identifier': 434369348, 'population': 836}
{'identifier': 430968590, 'population': 534}
{'identifier': 2000100687, 'population': 1376}
{'identifier': 2783160954, 'population': 1486}
{'identifier': 1534218794, 'population': 145}
{'identifier': 431043029, 'population': 1409}
{'identifier': 1255528482, 'population': 1726}
{'identifier': 435465434, 'population': 1436}
{'identifier': 1257471997, 'population': 223}
{'identifier': 2822641953, 'population': 1293}


In [58]:
agus.dictionary.get('candidates').get(955316231).get('time').append(123:{'identifier':123,'A*':12.34})

SyntaxError: invalid syntax (2393868262.py, line 1)

In [ ]:
agus.dictionary.get('candidates').get(955316231).get('time')[123] = {'identifier':123,'A*':12.34}

In [ ]:
agus.dictionary.get('candidates').get(955316231).get('time')

In [ ]:
attr(agus.dicitionary.get('candidates').get(955316231).get('time'))

In [ ]:
mi_diccionario = {'clave1': 'valor1', 'clave2': 'valor2'}
mi_diccionario['nueva_clave'] = 'nuevo_valor'
mi_diccionario['otra_clave'] = 'otro_valor'

In [ ]:
mi_diccionario

In [ ]:
agus.dictionary.get('intersections')
#agus.dictionary.get('intersections').get(434369348)

In [ ]:
agus.dictionary['intersections'][434369348]['whereto']

In [ ]:
agus.dictionary['intersections']

In [ ]:
for i in 

In [ ]:
import random
random.seed(24)
random.randint(0,1)

In [ ]:
import numpy as np
mi_array = np.array([0,1,1,1,1,0])

In [ ]:
mi_array

In [ ]:
np.count_nonzero(mi_array==1)

In [6]:
import json
import numpy as np
import random
import sys
from geographiclib.geodesic import Geodesic # pip install geographiclib
import heapq
from abc import ABC,abstractmethod



I was going to create a function that counts the **number of ones** in a given configuration/solution but I already have it done in **numpy**



I want this function to correct the number of ones to the number of ones I want

I am going to put here the **Problem** class.

In [7]:
class Problem:
    def __init__(self,file_name):
        with open(file_name,'r') as file:
            self.dictionary = json.load(file)
        self.dictionary['intersections'] = {inter['identifier']: inter for inter in self.dictionary.get('intersections')}# O(m)
        # en la linea de abajo estamos convirtiendo una lista de listas en un diccionario de diccionarios
        # no creo que haga mucha diferencia pero ya veremos
        self.dictionary['candidates'] = {candidate[0]:{"identifier":candidate[0],"population":candidate[1]} for candidate in self.dictionary.get('candidates')}
        self.dictionary['maxSpeedOfAllSpeeds'] = float('-inf') # definiendo la maxima velocida a menos infinito
        # Add the 'whereto' attribute to each intersection
        for inter in self.dictionary['intersections'].values():# O(m)
            inter['whereto'] = []

        # Populate the 'whereto' attribute based on the segments
        for segment in self.dictionary.get('segments'):# O(n)
            origin = segment['origin']#O(1)
            destination = segment['destination'] #O(1)
            distance = segment['distance'] #O(1)
            speed_kmh = segment['speed'] # O(1)

            # Convert speed from km/h to m/s
            speed_ms = speed_kmh * (1000 / 3600)
            #self.dictionary['mostRepeatedSpeed'].append(speed_ms)
            # Si tenemos una velocidad mayor a la predeterminada, la cogemos
            if(speed_ms > self.dictionary.get('maxSpeedOfAllSpeeds')):#O(1)
                self.dictionary['maxSpeedOfAllSpeeds'] = speed_ms
    
            # Calculate the cost
            cost = distance / speed_ms
    
            # Add the destination and cost to the 'whereto' attribute of the origin intersection
            #if origin in self.dictionary.get('intersections'): # O(1)
            self.dictionary.get('intersections').get(origin).get('whereto').append({'id': destination, 'cost': cost})
        for i in self.dictionary.get('intersections'):
            self.dictionary['intersections'][i]['whereto'] = sorted(self.dictionary.get('intersections').get(i).get('whereto'),key = lambda x:x['id'])
        
    

Down below we are going to have the **Search** class.

w.r.t **evaluation(self,solution)**

Notice that it does not matter if **solution[i]** is 0 and we calculate **get_time_a_star(initial,final)** since we are going to store it in memory. If we need this value in a future, we won't calculate it again. That is why we are storing it in memory.

Should we return **f_ = 1/f** since we are minimizing?

We are minimizing the **cost**

I think it is alright as it is since we are calculating the **average time a person would take to reach to any station** so we want to minimize this time.

In [8]:
class Search(ABC):
    def __init__(self,problem):
        self.problem = problem
        self.openDS = [] # open_data_structure
        self.nodesGenerated = 0
        self.initial = 0
        self.final = 0
    def insert(self,element): # siempre insertamos de la misma forma
        self.openDS.append(element)
    #@abstractmethod
    def extract():
        pass
    #@abstractmethod
    ##############################################################################################
    ######################################### evaluation #########################################
    ##############################################################################################
    def evaluation(self,solution):
        """
        Here is where we are going to store in memory the results of A* so that if in a near future we need it,
        we can go and look in memory, not performing all the calculations again. Also, bear in mind what was mentioned
        in the lab that if we are trying to minimize then we must take f_ = 1/f. In other words, if you want the
        highest score of the class, you want to transform a 10 to a 1/10 so that it is the smallest one of all.
        If you divide 1 over a number that is greater, then the ratio is going to be smaller.
        1/10 < 1/9. 10 is a better grade than 9 and as you want to keep the same information but minimizing,
        that is why we do the ratio. So, maybe we are going to have to do this here. We want to minimize the time
        we spend to go to a certain Service Station.
        :param solution: a given solution to be evaluated 
        """
        total_population = 0
        weight_per_station = 0
        for i in self.problem.dictionary.get('candidates').values():
            pop = i.get('population')
            total_population += pop
            initial = i.get('identifier')
            self.initial = initial
        
            for j in self.problem.dictionary.get('candidates').values():    
                final = j.get('identifier')
                self.final = final
                time_a_star = self.get_time_a_star(initial,final)
                weight_per_station += time_a_star * pop * solution[i]
                
        return weight_per_station / total_population
  ##############################################################################################
    ######################################### get_time_a_star #########################################
    ##############################################################################################
    def get_time_a_star(self,initial,final):
        
        if( not self.is_already_in_memory(initial,final)): # if it is NOT in memory
            # save it in memory
            return self.save_changes(initial,final)
        #otherwise just get it from memory
        return self.problem.dictionary.get('candidates').get(initial).get('time').get(final).get('A*')# get it from memory
           ##############################################################################################
    ######################################### is_already_in_memory #########################################
    ##############################################################################################
    def is_already_in_memory(self,initial,final):
        if ('time' in self.problem.dictionary.get('candidates').get(initial)):
            for i in self.problem.dictionary.get('candidates').get(initial).get('time').values():
                if(i.get('identifier') == final):
                    return True
        return False
        ##############################################################################################
    ######################################### save_changes #########################################
    ##############################################################################################
    def save_changes(self,initial,final):
        """
        The idea is saving a dictionary of dictionaries ('time') which for each candidate will store 
        where it can go and how much time it costs

        {'candidate1':{'identifier':,'population':,'time': {'identifier':,'A*':}},
        'candidate2':{'identifier':,'population':,'time':{'identifier':,'A*':}}}
        """
        instance_of_search = AStar(self.problem)
        time_a_star = instance_of_search.search(initial,final)
        if('time' in self.problem.dictionary.get('candidates').get(initial)):
            # just append it as it already exists
            self.problem.dictionary.get('candidates').get(initial).get('time')[final] = {'identifier':final,'A*':time_a_star}
            return time_a_star
        #create the attribute and store it
        self.problem.dictionary.get('candidates').get(initial)['time'] = dict()
        self.problem.dictionary.get('candidates').get(initial).get('time')[final] ={'identifier':final,'A*':time_a_star}
        return time_a_star
            
    def search(self):
       pass
    ##############################################################################################
    ############################## correctPossibleNumberStations #################################
    ##############################################################################################
    def correctPossibleNumberStations(self,configuration):
        """
        In this function we correct the number of ceros and ones to our needs.
        :param configuration: ndarray from numpy library representing a binary array, a configuration, a solution, a chromosome
        """
        # we get the number of ones
        number_of_ones_we_must_have = self.problem.dictionary.get('number_stations')
        number_of_ones_we_have = np.count_nonzero(configuration==1)
        if (number_of_ones_we_have < number_of_ones_we_must_have):
            # we must introduce some ones
            difference = number_of_ones_we_must_have - number_of_ones_we_have
            positions_where_zeros_are = np.where(configuration == 0)[0]
            new_positions_ones = np.random.choice(positions_where_zeros_are,difference, replace = False)
            configuration[new_positions_ones] = 1
        if (number_of_ones_we_have > number_of_ones_we_must_have):
            # we compute the difference 
            difference =  number_of_ones_we_have - number_of_ones_we_must_have
            positions_where_ones_are = np.where(configuration==1)[0]
            new_positions_zero = np.random.choice(positions_where_ones_are,difference,replace = False)
            configuration[new_positions_zero] = 0
        return configuration
    ##############################################################################################
    ################################### generateARandomSolution ##################################
    ##############################################################################################
    def generateARandomSolution(self):
        """
        Function to create a random solution.
        
        """
        length_of_array_of_candidates = len(self.problem.dictionary.get('candidates'))
        number_of_ones_we_need = self.problem.dictionary.get('number_stations')
        random_solution = np.zeros(length_of_array_of_candidates,dtype=int)
        positions_where_we_are_going_to_introduce_ones = np.random.choice(length_of_array_of_candidates,number_of_ones_we_need,replace = False)
        random_solution[positions_where_we_are_going_to_introduce_ones] = 1
        return random_solution
    ##############################################################################################
    ######################################## hillClimbing ########################################
    ##############################################################################################
    def hillClimbing(self,initialSolution):
        """
        This is where we exploit, hill climb. We revise our neighbours.
        """
        #Lesson 7 Slide 13
        currentSolution = initialSolution
        currentScore = self.evaluation(currentSolution)
        improves = True
        while (improves):
            improves = False
            neighbours = self.generateNeighbours(currentSolution)
            for neighbour in neighbours:
                score = self.evaluation(neighbour)
                if (score > currentScore):
                    currentSolution = neighbour
                    currentScore = score
                    improves = True
        return currentScore
    ##############################################################################################
    ######################################## generateNeighbours ##################################
    ##############################################################################################
    def generateNeighbours(self,currentSolution):
        """
        We generate neighbours by just changing one bit at a time. Permutation.
        Notice that all the neighbours are not valid solutions. Maybe we can optimize this in a future.
        """
        neighbours = []
        for i in range(0,len(currentSolution)): # for the length of the array
            neighbour_ = currentSolution.copy()

            negihbour_[i] = 1 - neighbour_[i] # 1-0 is 1 and 1-1 = 0 so that we change the bit 
            condition = checkIfThisIsASolution(neighbour_) # if it is a valid solution
            if (condition):
                neighbours.append(negihbour_) # we put it into our bag of solutions
                
        return np.array(neighbours)
    ##############################################################################################
    ######################################## checkIfThisIsASolution ##############################
    ##############################################################################################
    def checkIfThisIsASolution(self,solution):
        """
        Checks if a given solution is valid.
        :param solution: given solution
        :return boolean: returns a boolean
        """
        number_of_ones_in_this_solution = np.count_nonzero(solution==1) # gets the number of zeros we have in the solution passed by parameter
        return number_of_ones_in_this_solution == self.problem.dictionary.get('number_stations') # returns true if it has the number of stations 
        #we must submit
    

I am going to put here **A\***.

We must handle the case in which **A\*** gives an infinte value. We must put the evaluation function result to 0.

In [ ]:
class AStar(Search):# takes into account g(n), not only h(n)
    ##############################################################################################
    ############################################# insert #########################################
    ##############################################################################################
    def insert(self,element):
         # element is a node
        """self.openDS is by default a deque() (see Search __init__) so we
        have to convert deque() into a list"""
        self.openDS = list(self.openDS)
        heuristic = (self.computeHeuristic(element)/self.problem.dictionary.get('maxSpeedOfAllSpeeds'))+element.accumulatedCost
        #print('\n-----------\n'.join(map(str,self.openDS)))
        heapq.heappush(self.openDS,(heuristic,element)) # element is going to be a paired value (h,Node)
    ##############################################################################################
    ############################################ extract #########################################
    ##############################################################################################
    def extract(self): #O(1)
        # tenemos que extraer el que menor heurística tiene --> la heurística hace de prioridad
        return heapq.heappop(self.openDS)[1] # heapq es una priorityQueue sin ser una Queue sino una Heap
    ##############################################################################################
    ######################################## computeHeuristic ####################################
    ##############################################################################################
    def computeHeuristic(self,node_param): #O(1)
        """self.openDS is by default a deque() (see Search __init__) so we
        have to convert deque() into a list"""
        self.openDS = list(self.openDS) # medios para obtener lo que queremos
        goalId = self.final # Obtenemos estado final
        coord_1 = (node_param.state.longitude, node_param.state.latitude) # (longitude,latitude)
        coord_2 = (self.problem.dictionary.get('intersections').get(goalId).get('longitude'), 
        self.problem.dictionary.get('intersections').get(goalId).get('latitude'))  # (longitude,latitude)
        # Usar el elipsoide WGS84 para calcular la distancia
        geod = Geodesic.WGS84 # cosas de la librería
        resultado = geod.Inverse(coord_1[0], coord_1[1], coord_2[0], coord_2[1]) # cosas de la librería
        # Distancia en metros
        distancia = resultado['s12'] 
        return distancia
         ##############################################################################################
    ######################################### search #########################################
    ##############################################################################################
    def search(self,initial,final): # O(n) # y siempre buscamos de la misma forma
        """:param search_param: strategy to use
        
        :returns: empty list of list of actions"""
        self.initializeOpen(initial) # inicializo nodo raiz # O(1)
        self.insert(self.root)
        while len(self.openDS)!=0:    
            node = self.extract() # O(1) 
            self.exploredNodes +=1
            if node.state.state not in self.explored:
                if(self.testGoal(node,final)): 
                    self.depth = node.depth
                    self.totalCost = node.accumulatedCost
                    return node.accumulatedCost # the accumulated cost of the last node is the total cost of the path and that is exactly what we want
                successors1 = self.expand(node) # O(n)
                if (len(successors1)>0):
                    self.expandedNodes+=1
                for  successor in successors1: # O(n)
                    self.insert(successor) # O(1)
                self.explored.add(node.state.state) #  node.state es el objeto y node.state.state es la variable en el objeto state
        print("Solución no encontrada y hemos recorrido todo el árbol")
        # if A* gives an NaN result, we are going to be here since there is no path
        return float('inf')
    """notice that we work with a tuple
    so if we want to return a node we must say tuple[1]
    where the tuple is (heuristic,node)"""
    ##############################################################################################
    ######################################## initializeOpen ######################################
    ##############################################################################################
    def initializeOpen(self,initial): # O(1)
        longitudeInitialNode = self.problem.dictionary.get('intersections').get(initial).get('longitude')
        latitudeInitialNode = self.problem.dictionary.get('intersections').get(initial).get('latitude')
        self.root = Node(None,State(initial,longitudeInitialNode,latitudeInitialNode),Action(None,initial,0),0,0) # no estoy seguro si para llegar al nodo raiz action == None
        self.nodesGenerated+=1
        self.root.momento = self.nodesGenerated
    #################################################################################
    ####################             testGoal              ##########################
    #################################################################################
    def testGoal(self,node,final):# O(1)
        return final == node.state.state# node.state es de tipo State y node.state.state es de tipo int

Let's create a **RandomSearch** class that will inherit from **Search**.

In [10]:
class RandomSearch(Search):
    def search(self,MaxIters):
        """
        This function is intended to solve the problem. At least, give a solution.
        As it is Random, I assume we are going to be exploiting all the time. Not really, we are going to be exploiting when we are evaluating 
        a given solution and exploring when we generate a random solution. The idea here is to balance exploitaion and exploration. I think
        it would be nice to have this one on the class RandomSearch, not here in Search.

        :param MaxIters: maximum of iterations you want to compute.
        """
        # Lesson 7 slide 27
        solution = None
        iteration = 0
        while (iteration < MaxIters):
            x = self.generateARandomSolution()
            x_ = self.hillClimbing(x)
            if(self.evaluation(x_) > self.evaluation(solution)):
                solution = x_
        return solution

Let's try the search **RandomSearch**

In [ ]:
problem = Problem('calle_del_virrey_morcillo_albacete_250_3_candidates_15_ns_4.json')
agus = RandomSearch(problem)
agus.search(20)

I am going to **test** the *correctPossibleNumberStations* function

In [ ]:
problem = Problem('calle_del_virrey_morcillo_albacete_250_3_candidates_15_ns_4.json')
search_class = RandomSearch(problem) 

In [ ]:
search_class.correctPossibleNumberStations(np.array([0,1,0,1,1,1,1,1,1,1,1,1]))

In [ ]:
search_class.correctPossibleNumberStations(np.array([0,1,0,0,0,0,0,0,0,0,0,0]))

In [ ]:
search_class.correctPossibleNumberStations(np.array([0,1,0,0,0,1,1,0,0,1,0,0]))

The **correctPossibleNumberStations** function works 😄.

In [ ]:
search_class.generateARandomSolution()

A little test of **inheritance**.

In [ ]:
class Shape(ABC):
    def __init__(self,number_of_vertices):
        self.number_of_vertices = number_of_vertices
class Circle(Shape):
    pass
    #def __init__(self,number_of_vertices):
     #   super().__init__(number_of_vertices)

In [ ]:
circle = Circle(0)

In [ ]:
circle.number_of_vertices

In [ ]:
search_class.problem.dictionary.get('candidates')

This is going to be our **GeneticAlgorithmSearch**

In [ ]:
class GeneticAlgorithm(Search):
    def search(self):
        #Lesson 8 Slide 18
        p = generate_population() # create candidate solutions (individuals)
        evaluate(p) # obtains  their score
        while(stop_condition==false):
            p_ = select_population(p) # Selects some individuals by score
            crossover(p_) #crosses pairs of selected individuals
            mutation(p_) # mutates the crossed individuals
            evaluate(p_) # obtains the score of the new individuals
            p = combine(p,p_) # forms the new generation
            