In [1]:
import json
class Agustin:
    def __init__(self):
        self.dictionary = None
        with open('calle_del_virrey_morcillo_albacete_250_3_candidates_15_ns_4.json','r') as file:
             self.dictionary = json.load(file)
        self.dictionary['intersections'] = {inter['identifier']: inter for inter in self.dictionary.get('intersections')}# O(m)
        
        # Add the 'whereto' attribute to each intersection
        for inter in self.dictionary['intersections'].values():# O(m)
            inter['whereto'] = []

        # Populate the 'whereto' attribute based on the segments
        for segment in self.dictionary.get('segments'):# O(n)
            origin = segment['origin']#O(1)
            destination = segment['destination'] #O(1)
            distance = segment['distance'] #O(1)
            speed_kmh = segment['speed'] # O(1)

            # Convert speed from km/h to m/s
            speed_ms = speed_kmh * (1000 / 3600)
            #self.dictionary['mostRepeatedSpeed'].append(speed_ms)
            # Si tenemos una velocidad mayor a la predeterminada, la cogemos
            #if(speed_ms > self.dictionary.get('maxSpeedOfAllSpeeds')):#O(1)
            #    self.dictionary['maxSpeedOfAllSpeeds'] = speed_ms
    
            # Calculate the cost
            cost = distance / speed_ms
    
            # Add the destination and cost to the 'whereto' attribute of the origin intersection
            #if origin in self.dictionary.get('intersections'): # O(1)
            self.dictionary.get('intersections').get(origin).get('whereto').append({'id': destination, 'cost': cost})
        #for i in self.dictionary.get('intersections'):
        #    self.dictionary.get(i)['whereto'] = sorted(self.dictionary.get('whereto'),key = lambda x:x['id'])
        for i in self.dictionary.get('intersections'):
            self.dictionary['intersections'][i]['whereto'] = sorted(self.dictionary.get('intersections').get(i).get('whereto'),key = lambda x:x['id'])

In [2]:
agus = Agustin()

In [3]:
agus.dictionary.get('candidates')
agus.dictionary['candidates'] = {candidate[0]:{"identifier":candidate[0],"population":candidate[1]} for candidate in agus.dictionary.get('candidates')}

In [4]:
agus.dictionary.get('candidates')

{955316231: {'identifier': 955316231, 'population': 875},
 1736146191: {'identifier': 1736146191, 'population': 1827},
 11303171544: {'identifier': 11303171544, 'population': 733},
 430968594: {'identifier': 430968594, 'population': 661},
 430968596: {'identifier': 430968596, 'population': 397},
 434369348: {'identifier': 434369348, 'population': 836},
 430968590: {'identifier': 430968590, 'population': 534},
 2000100687: {'identifier': 2000100687, 'population': 1376},
 2783160954: {'identifier': 2783160954, 'population': 1486},
 1534218794: {'identifier': 1534218794, 'population': 145},
 431043029: {'identifier': 431043029, 'population': 1409},
 1255528482: {'identifier': 1255528482, 'population': 1726},
 435465434: {'identifier': 435465434, 'population': 1436},
 1257471997: {'identifier': 1257471997, 'population': 223},
 2822641953: {'identifier': 2822641953, 'population': 1293}}

In [5]:
agus.dictionary.get('intersections')
#agus.dictionary.get('intersections').get(434369348)

NameError: name 'agus' is not defined

In [27]:
agus.dictionary['intersections'][434369348]['whereto']

[{'id': 11303171544, 'cost': 1.58064},
 {'id': 1529477806, 'cost': 9.069119999999998}]

In [14]:
agus.dictionary['intersections']

{430968565: {'identifier': 430968565,
  'longitude': -1.8602834,
  'latitude': 38.9991511,
  'whereto': [{'id': 1257471995, 'cost': 6.619199999999999},
   {'id': 1529477842, 'cost': 10.40604}]},
 430968569: {'identifier': 430968569,
  'longitude': -1.858918,
  'latitude': 38.9982214,
  'whereto': [{'id': 430968573, 'cost': 1.734}]},
 430968573: {'identifier': 430968573,
  'longitude': -1.8588948,
  'latitude': 38.9980972,
  'whereto': [{'id': 4575714132, 'cost': 0.44832},
   {'id': 431043029, 'cost': 2.22768}]},
 430968590: {'identifier': 430968590,
  'longitude': -1.8587723,
  'latitude': 38.9983034,
  'whereto': [{'id': 430968592, 'cost': 1.9261199999999996},
   {'id': 430968569, 'cost': 1.9516799999999999}]},
 430968592: {'identifier': 430968592,
  'longitude': -1.8589007,
  'latitude': 38.9984077,
  'whereto': [{'id': 430968594, 'cost': 17.671200000000002},
   {'id': 571129950, 'cost': 9.5118}]},
 430968594: {'identifier': 430968594,
  'longitude': -1.8602064,
  'latitude': 38.9992

In [ ]:
for i in 

In [22]:
import random
random.seed(24)
random.randint(0,1)

1

In [27]:
import numpy as np
mi_array = np.array([0,1,1,1,1,0])

In [28]:
mi_array

array([0, 1, 1, 1, 1, 0])

In [29]:
np.count_nonzero(mi_array==1)

4

In [88]:
import json
import numpy as np
import random
import sys
sys.path.append('c:\\users\\agus\\appdata\\local\\programs\\python\\python312\\lib\\site-packages')
from geographiclib.geodesic import Geodesic # pip install geographiclib
import heapq
from abc import ABC,abstractmethod

Me iba a crear una funcion para que me cuente el **numero de unos** en la solucion pero ya lo tengo hecho en **numpy**

Quiero que esta funcion corrija el numero de unos al numero que yo quiera

I am going to put here the **Problem** class.

In [89]:
class Problem:
    def __init__(self,file_name):
        with open(file_name,'r') as file:
            self.dictionary = json.load(file)
        self.dictionary['intersections'] = {inter['identifier']: inter for inter in self.dictionary.get('intersections')}# O(m)
        # en la linea de abajo estamos convirtiendo una lista de listas en un diccionario de diccionarios
        # no creo que haga mucha diferencia pero ya veremos
        self.dictionary['candidates'] = {candidate[0]:{"identifier":candidate[0],"population":candidate[1]} for candidate in self.dictionary.get('candidates')}
        self.dictionary['maxSpeedOfAllSpeeds'] = float('-inf') # definiendo la maxima velocida a menos infinito
        # Add the 'whereto' attribute to each intersection
        for inter in self.dictionary['intersections'].values():# O(m)
            inter['whereto'] = []

        # Populate the 'whereto' attribute based on the segments
        for segment in self.dictionary.get('segments'):# O(n)
            origin = segment['origin']#O(1)
            destination = segment['destination'] #O(1)
            distance = segment['distance'] #O(1)
            speed_kmh = segment['speed'] # O(1)

            # Convert speed from km/h to m/s
            speed_ms = speed_kmh * (1000 / 3600)
            #self.dictionary['mostRepeatedSpeed'].append(speed_ms)
            # Si tenemos una velocidad mayor a la predeterminada, la cogemos
            if(speed_ms > self.dictionary.get('maxSpeedOfAllSpeeds')):#O(1)
                self.dictionary['maxSpeedOfAllSpeeds'] = speed_ms
    
            # Calculate the cost
            cost = distance / speed_ms
    
            # Add the destination and cost to the 'whereto' attribute of the origin intersection
            #if origin in self.dictionary.get('intersections'): # O(1)
            self.dictionary.get('intersections').get(origin).get('whereto').append({'id': destination, 'cost': cost})
        for i in self.dictionary.get('intersections'):
            self.dictionary['intersections'][i]['whereto'] = sorted(self.dictionary.get('intersections').get(i).get('whereto'),key = lambda x:x['id'])

Down below we are going to have the **Search** class.

In [90]:
class Search(ABC):
    def __init__(self,problem):
        self.problem = problem
        self.openDS = []
    def insert(self,element): # siempre insertamos de la misma forma
        self.openDS.append(element)
    #@abstractmethod
    def extract():
        pass
    #@abstractmethod
    def evaluation():
        pass
    def search(self,search_param): # O(n) # y siempre buscamos de la misma forma
        """:param search_param: strategy to use
        
        :returns: empty list of list of actions"""
        search_param.insert(self.root)
        while len(search_param.openDS)!=0:    
            node = search_param.extract() # O(1) 
            self.exploredNodes +=1
            if node.state.state not in self.explored:
                if(self.testGoal(node)): 
                    self.depth = node.depth
                    self.totalCost = node.accumulatedCost
                    return self.recoverPath(node,[],0)
                successors1 = self.expand(node) # O(n)
                if (len(successors1)>0):
                    self.expandedNodes+=1
                for  successor in successors1: # O(n)
                    search_param.insert(successor) # O(1)
                self.explored.add(node.state.state) #  node.state es el objeto y node.state.state es la variable en el objeto state
        print("Solución no encontrada y hemos recorrido todo el árbol")
        return search_param.openDS
    """notice that we work with a tuple
    so if we want to return a node we must say tuple[1]
    where the tuple is (heuristic,node)"""
    def extract(self): #O(1)
        # tenemos que extraer el que menor heurística tiene --> la heurística hace de prioridad
        return heapq.heappop(self.openDS)[1] # heapq es una priorityQueue sin ser una Queue sino una Heap
    def computeHeuristic(self,node_param): #O(1)
        """self.openDS is by default a deque() (see Search __init__) so we
        have to convert deque() into a list"""
        self.openDS = list(self.openDS) # medios para obtener lo que queremos
        goalId = self.problem.dictionary.get('final') # Obtenemos estado final
        coord_1 = (node_param.state.longitude, node_param.state.latitude) # (longitude,latitude)
        coord_2 = (self.problem.dictionary.get('intersections').get(goalId).get('longitude'), 
                   self.problem.dictionary.get('intersections').get(goalId).get('latitude'))  # (longitude,latitude)
        # Usar el elipsoide WGS84 para calcular la distancia
        geod = Geodesic.WGS84 # cosas de la librería
        resultado = geod.Inverse(coord_1[0], coord_1[1], coord_2[0], coord_2[1]) # cosas de la librería
        # Distancia en metros
        distancia = resultado['s12'] 
        return distancia
    def correctPossibleNumberStations(self,configuration):
        """
        In this function we correct the number of ceros and ones to our needs.
        :param configuration: ndarray from numpy library representing a binary array, a configuration, a solution, a chromosome
        """
        # we get the number of ones
        number_of_ones_we_must_have = self.problem.dictionary.get('number_stations')
        number_of_ones_we_have = np.count_nonzero(configuration==1)
        if (number_of_ones_we_have < number_of_ones_we_must_have):
            # we must introduce some ones
            difference = number_of_ones_we_must_have - number_of_ones_we_have
            positions_where_zeros_are = np.where(configuration == 0)[0]
            new_positions_ones = np.random.choice(positions_where_zeros_are,difference, replace = False)
            configuration[new_positions_ones] = 1
        if (number_of_ones_we_have > number_of_ones_we_must_have):
            # we compute the difference 
            difference =  number_of_ones_we_have - number_of_ones_we_must_have
            positions_where_ones_are = np.where(configuration==1)[0]
            new_positions_zero = np.random.choice(positions_where_ones_are,difference,replace = False)
            configuration[new_positions_zero] = 0
        return configuration
    def generateARandomSolution(self):
        """
        Function to create a random solution.
        
        """
        length_of_array_of_candidates = len(self.problem.dictionary.get('candidates'))
        number_of_ones_we_need = self.problem.dictionary.get('number_stations')
        random_solution = np.zeros(length_of_array_of_candidates,dtype=int)
        positions_where_we_are_going_to_introduce_ones = np.random.choice(length_of_array_of_candidates,number_of_ones_we_need,replace = False)
        random_solution[positions_where_we_are_going_to_introduce_ones] = 1
        return random_solution
    def randomizedLocalSearch(self,MaxIters):
        """
        This function is intended to solve the problem. At least, give a solution.
        As it is Random, I assume we are going to be exploiting all the time.

        :param MaxIters: maximum of iterations you want to compute.
        """
        # Lesson 7 slide 27
        solution = None
        iteration = 0
        while (iteration < MaxIters):
            x = self.generateARandomSolution()
            x_ = self.hillClimbing(x)
            if(evaluation(x_) > evaluation(solution)):
                solution = x_
        return solution
    def hillClimbing(self,initialSolution):
        """
        This is where we exploit, hill climb. We revise our neighbours.
        """
        #Lesson 7 Slide 13
        currentSolution = initialSolution
        currentScore = evaluation(currentSolution)
        improves = True
        while (improves):
            improves = False
            neighbours = generateNeighbours(currentSolution)
            for neighbour in neighbours:
                score = evaluation(neighbour)
                if (score > currentScore):
                    currentSolution = neighbour
                    currentScore = score
                    improves = True
        return currentScore
    def generateNeighbours(self,currentSolution):
        """
        We generate neighbours by just changing one bit at a time. Permutation.
        """
        neighbours = []
        for i in range(0,len(currentSolution)):
            neighbour_ = currentSolution.copy()

            negihbour_[i] = 1 - neighbour_[i]
            condition = checkIfThisIsASolution(neighbour_)
            if (condition):
                neighbours.append(negihbour_)
                
        return np.array(neighbours)
    def checkIfThisIsASolution(self,solution):
        """
        Checks if a given solution is valid.
        :param solution: given solution
        :return boolean: returns a boolean
        """
        number_of_ones_in_this_solution = np.count_nonzero(solution==1)
        return number_of_ones_in_this_solution == self.problem.dictionary.get('number_stations')

I am going to put here **A\***.

In [95]:
class AStar(Search):# takes into account g(n), not only h(n)
    def insert(self,element):
         # element is a node
        """self.openDS is by default a deque() (see Search __init__) so we
        have to convert deque() into a list"""
        self.openDS = list(self.openDS)
        heuristic = (super().computeHeuristic(element)/self.problem.dictionary.get('maxSpeedOfAllSpeeds'))+element.accumulatedCost
        #print('\n-----------\n'.join(map(str,self.openDS)))
        heapq.heappush(self.openDS,(heuristic,element)) # element is going to be a paired value (h,Node)

Let's create a **RandomSearch** class that will inherit from **Search**.

In [91]:
class RandomSearch(Search):
    def __init__(self,problem):
        super().__init__(problem)

I am going to **test** the *correctPossibleNumberStations* function

In [92]:
problem = Problem('calle_del_virrey_morcillo_albacete_250_3_candidates_15_ns_4.json')
search_class = RandomSearch(problem) 

In [82]:
search_class.correctPossibleNumberStations(np.array([0,1,0,1,1,1,1,1,1,1,1,1]))

array([0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0])

In [83]:
search_class.correctPossibleNumberStations(np.array([0,1,0,0,0,0,0,0,0,0,0,0]))

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1])

In [84]:
search_class.correctPossibleNumberStations(np.array([0,1,0,0,0,1,1,0,0,1,0,0]))

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0])

The **correctPossibleNumberStations** function works 😄.

In [94]:
search_class.generateARandomSolution()

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0])

A little test of **inheritance**.

In [64]:
class Shape(ABC):
    def __init__(self,number_of_vertices):
        self.number_of_vertices = number_of_vertices
class Circle(Shape):
    def __init__(self,number_of_vertices):
        super().__init__(number_of_vertices)

In [65]:
circle = Circle(0)

In [66]:
circle.number_of_vertices

0

In [87]:
search_class.problem.dictionary.get('candidates')

{955316231: {'identifier': 955316231, 'population': 875},
 1736146191: {'identifier': 1736146191, 'population': 1827},
 11303171544: {'identifier': 11303171544, 'population': 733},
 430968594: {'identifier': 430968594, 'population': 661},
 430968596: {'identifier': 430968596, 'population': 397},
 434369348: {'identifier': 434369348, 'population': 836},
 430968590: {'identifier': 430968590, 'population': 534},
 2000100687: {'identifier': 2000100687, 'population': 1376},
 2783160954: {'identifier': 2783160954, 'population': 1486},
 1534218794: {'identifier': 1534218794, 'population': 145},
 431043029: {'identifier': 431043029, 'population': 1409},
 1255528482: {'identifier': 1255528482, 'population': 1726},
 435465434: {'identifier': 435465434, 'population': 1436},
 1257471997: {'identifier': 1257471997, 'population': 223},
 2822641953: {'identifier': 2822641953, 'population': 1293}}